<?php

namespace CarBundle\Repository;

use CarBundle\Entity\Car;
use Doctrine\ORM\Query\Expr;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository {
	/**
	 * @return array
	 */
	public function findCarsWithDetails() {
		$qb    = $this->createQueryBuilder( 'c' );
		$query = $qb->select( 'c, mk, ml' )
		            ->join( 'c.make', 'mk' )
		            ->join( 'c.model', 'ml' )
		            ->getQuery();

		return $query->getResult();
	}

	/**
	 * @param int $id
	 *
	 * @return Car
	 * @throws \Doctrine\ORM\NoResultException
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 */
	public function findCarWithDetailsById( $id ) {
		$qb = $this->createQueryBuilder( 'c' );

		$query = $qb->select( 'c, mk, ml' )
		            ->join( 'c.make', 'mk' )
		            ->join( 'c.model', 'ml' )
		            ->where( 'c.id = :id' )
		            ->setParameter( 'id', $id )
		            ->getQuery();

		return $query->getSingleResult();
	}
}
