services:
#    car.example:
#        class: CarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    car.data_checker:
        class: CarBundle\Service\DataChecker
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%require_photos_to_promote%"

    car.command.data_check:
        class: CarBundle\Command\AbcCheckCarsCommand
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@car.data_checker"
        tags:
            - { name: console.command }